### ISSUE TITLE
Undersøke database-struktur

### ISSUE THREAD

**Issue by plankeP** [Bjorgeh/rapportsystem-backend#1]

**Comment by Bjorgeh** [comment]
Skal vi lagre rapporter som json i databasen? 
Hvordan skal tilganger til rapporter og funksjoner i databasen fordeles?

**Comment by rudabrah** [comment]
Jeg tror JSON vil være den beste måten for rapporter. Tilganger må vi styre i brukertyper tenker jeg.  Dette må vi finne noe litteratur på.

**Comment by rudabrah** [comment]
Storing custom visualizations and reports in a MySQL database, especially if they are user-specific, is a reasonable approach. Using JSON for this purpose is a common and flexible choice. JSON allows you to store complex data structures in a format that can be easily manipulated and queried.

Here's a general guideline on how you can structure and store custom visualizations in MySQL using JSON:

### Database Table Structure:

Create a table to store user-specific visualizations and reports. The structure may look like this:

```sql
CREATE TABLE user_visualizations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    visualization_name VARCHAR(255),
    visualization_data JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
```

In this example:

- `id`: Unique identifier for each visualization.
- `user_id`: The ID of the user who created the visualization.
- `visualization_name`: A user-defined name for the visualization.
- `visualization_data`: JSON field to store the actual visualization configuration.
- `created_at` and `updated_at`: Timestamps for tracking when the visualization was created and last updated.

### Storing Custom Visualizations:

When a user creates a custom visualization, you can store it in the `user_visualizations` table. The `visualization_data` field would contain the JSON representation of the visualization configuration. For example:

```json
{
  "type": "bar",
  "data": {
    "labels": ["January", "February", "March"],
    "datasets": [
      {
        "label": "My Data",
        "data": [10, 20, 15],
        "backgroundColor": "rgba(75, 192, 192, 0.2)",
        "borderColor": "rgba(75, 192, 192, 1)",
        "borderWidth": 1
      }
    ]
  },
  "options": {
    "scales": {
      "y": {
        "beginAtZero": true
      }
    }
  }
}
```

### Retrieving and Using Custom Visualizations:

When a user wants to load a saved visualization, fetch the data from the database and use it to configure the visualization tool on the client side. For example, if you're using a JavaScript charting library like Chart.js:

```javascript
// Assuming fetchedData is the JSON data retrieved from the database
const fetchedData = /* ... */

const ctx = document.getElementById('myChart').getContext('2d');
const myChart = new Chart(ctx, JSON.parse(fetchedData.visualization_data));
```

### Considerations:

1. **Security:** Ensure that user-specific data is properly sanitized and validated to prevent security vulnerabilities such as SQL injection.

2. **Validation:** Implement validation on the client and server sides to ensure that the stored JSON is valid and can be correctly interpreted by your visualization tool.

3. **Versioning:** If your visualization configurations may evolve over time, consider versioning the JSON structures to handle updates gracefully.

4. **User Interface:** Create a user-friendly interface for users to create, edit, and manage their custom visualizations.

Using JSON for this purpose allows you to store complex visualization configurations without having to create a separate table for each type of visualization or report, providing flexibility and ease of maintenance.

**Comment by Bjorgeh** [comment]
Det er nok lurt! Vi får notere hvilke behov vi har og begrunne de i en liten tekst.

JSON crack er fin for å visualisere JSON 😎 - Tok eksempel fra det du sendte over
![image](https://github.com/Bjorgeh/rapportsystem-backend/assets/122554284/9242539f-8961-4937-b2a0-96d7428d32c6)

**Comment by Bjorgeh** [comment]
Lukker denne da SQL struktur for brukere og rapporter er ok.
