### ISSUE TITLE
Lage diagram for SQL struktur

### ISSUE THREAD

**Issue by Bjorgeh** [Bjorgeh/rapportsystem-backend#18]

**Comment by rudabrah** [comment]
Har begynt å lage diagram i MySQL workbench diagramverktøy. Legges inn ASAP

**Comment by Bjorgeh** [comment]
Her er en oversikt over det foreløpige SQL oppsettet:
![image](https://github.com/Bjorgeh/rapportsystem-backend/assets/122554284/6e106dd1-7ab3-4560-b95d-41f53f3e38ee)

**Comment by rudabrah** [comment]
Dette er for brukere?

**Comment by Bjorgeh** [comment]
Det er vell brukerene som skal ha rapportene bundet til seg ut fra hvilken bruker de har

**Comment by rudabrah** [comment]
Nei, det stemmerr nok bra. Jeg lager tabeller for de forskjelliger rapportene. Etter at jeg har en prototyp oppe kan vi se på å flette dette sammen.

**Comment by rudabrah** [comment]
![Database_rapporter_struktur](https://github.com/Bjorgeh/rapportsystem-backend/assets/47385921/e01d67c6-6f02-404e-bdaa-b7680ae5f14e)

**Comment by rudabrah** [comment]
-- MySQL Script generated by MySQL Workbench
-- Tue Jan  9 19:09:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Disarapport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disarapport` (
  `RapportID` INT NOT NULL AUTO_INCREMENT,
  `Skift` VARCHAR(45) NOT NULL,
  `Dato og klokkeslett` DATETIME NOT NULL,
  `Antall formet` INT NOT NULL,
  `Antall støpt` INT NOT NULL,
  `Kommentar` VARCHAR(250) NULL,
  `Modellbrettnr` INT NOT NULL,
  PRIMARY KEY (`RapportID`),
  UNIQUE INDEX `RapportID_UNIQUE` (`RapportID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sandanalyse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sandanalyse` (
  `ID` INT NOT NULL,
  `Dato` DATE NOT NULL,
  `Klokkeslett` TIME NOT NULL,
  `Fuktighet` DECIMAL NOT NULL,
  `Trykkstyrke` DECIMAL NOT NULL,
  `Pakningsgrad` DECIMAL NOT NULL,
  `Glødetap` DECIMAL NOT NULL,
  `Spaltestyrke` DECIMAL NOT NULL,
  `Aktiv Bentonitt` DECIMAL NOT NULL,
  `Slaminnhold` DECIMAL NOT NULL,
  `Sikteanalyse` DECIMAL NOT NULL,
  `Sandanalysecol` DECIMAL NOT NULL,
  `Kompresibilitet` DECIMAL NOT NULL,
  `Sandtemperatur` DECIMAL NOT NULL,
  `Signatur` VARCHAR(20) CHARACTER SET 'utf16' NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Skrap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Skrap` (
  `idSkrap` INT NOT NULL,
  `Katalognummer` INT NOT NULL,
  `Antall_bestilt` INT NOT NULL,
  `Antall_manko` INT NOT NULL,
  `Pris_Pr_del` FLOAT NULL,
  `Sum_pris` FLOAT GENERATED ALWAYS AS (Antall_manko * Pris_Pr_del) VIRTUAL,
  `Skrapcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idSkrap`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Smelterapport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Smelterapport` (
  `RegistreringsID` INT NOT NULL,
  `Ovnsnummer` INT NOT NULL,
  `Dato` DATE NOT NULL,
  `Klokkeslett` TIME NOT NULL,
  `Kg_eget` FLOAT NOT NULL,
  `Kg_stal` FLOAT NOT NULL,
  `Totalvekt_smelte` FLOAT GENERATED ALWAYS AS (Kg_eget + Kg_stal) VIRTUAL,
  `KG_Karbon` FLOAT NOT NULL,
  `KG_malm` FLOAT NOT NULL,
  `KG_FeSi` FLOAT NOT NULL,
  `KG_FeP` FLOAT NOT NULL,
  `KwH_for_smelte` DOUBLE NOT NULL,
  `KwH_etter_smelte` DOUBLE NOT NULL,
  `SUM_KwH_Brukt` DOUBLE GENERATED ALWAYS AS (KwH_for_smelte + KwH_etter_smelte) VIRTUAL,
  PRIMARY KEY (`RegistreringsID`))
ENGINE = InnoDB
KEY_BLOCK_SIZE = 16;


-- -----------------------------------------------------
-- Table `mydb`.`borrprove_og_boyeprove`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`borrprove_og_boyeprove` (
  `ProveID` INT NOT NULL,
  `Deltype` VARCHAR(45) NOT NULL,
  `Ovn` VARCHAR(45) NOT NULL,
  `Katalognummer` INT NULL,
  `Antall_proveobjekter` INT NULL,
  `Ordernummer` VARCHAR(45) NOT NULL,
  `Godkjent` TINYINT NOT NULL COMMENT '\n',
  `Dato` DATE NOT NULL,
  `Tid` TIME NOT NULL,
  `Signatur` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ProveID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
