### ISSUE TITLE
Begynne å lage backend-utkast

### ISSUE THREAD

**Issue by plankeP** [Bjorgeh/rapportsystem-backend#3]

**Comment by Bjorgeh** [comment]
Opprettet google server for SQL og back-end. Ny server om 3 måneder.

**Comment by Bjorgeh** [comment]
![Image](https://github.com/Bjorgeh/rapportsystem-backend/assets/122554284/ee3a41f5-54d9-4510-8d3f-ca4dc78c8e72)

**Comment by Bjorgeh** [comment]
Satt opp API med APIkey krav og SQL tilkobling

**Comment by Bjorgeh** [comment]
Fjernet APiKey - lagt til sessions med timestamp i database i stedet.
