### ISSUE TITLE
Erstatte cookies autentisering

### ISSUE THREAD

**Issue by anzure** [Bjorgeh/rapportsystem-backend#51]
Forslag: Fjerne cookies autentisering og bare gi en session ID. Hvilken type autentsering skal brukes over API-et? Det bør også dokumenteres hvor session ID (også kalt auth token) skal sendes når backend API-et aksesseres.

**Comment by Bjorgeh** [comment]
Fikser dette med JWT tokens så snart jeg er hjemme. 👍
