### ISSUE TITLE
Sjekk ut Doxygen og SQL Grafana

### ISSUE THREAD

**Issue by Bjorgeh** [Bjorgeh/rapportsystem-backend#52]

**Comment by Bjorgeh** [comment]
doxygen - ikke docusign

**Comment by rudabrah** [comment]
Dette bør håndteres i FrontEnd. Heller kjøre rett fra react npm libraries.

**Comment by Bjorgeh** [comment]
Lukker denne da dette ikke passer for vårt prosjekt.
