### ISSUE TITLE
Get my user information endpoint

### ISSUE THREAD

**Issue by anzure** [Bjorgeh/rapportsystem-backend#58]
Create new API endpoint for getting information about the user that is sending the request.

Example response from backend:

```javascript
{
  userId: 453,
  firstName: 'Ola',
  lastName: 'Nordmann',
  username: 'ola.nordmann@viken.no',
  accountType: 'admin'
}
```

**Comment by rudabrah** [comment]
Jobber på denne. Merk, vi skal kun lage "fellesbrukere" knyttet til stasjoner. Eks:
{
userId: 4
name: "Vekt Operatør"
email: "vekt@bedrift.no"
accountType: "Operator"
}
